### ISSUE TITLE
Remove "skip" from Model retrieval examples in README

### ISSUE THREAD

**Issue by travs** [openworm/owmeta#165]
Some examples [here](https://github.com/openworm/PyOpenWorm/blob/25d7ea37c711203b1f3d408dabaa2e23a4cea8ea/README.md#modelling-data) won't be run as doctests yet because there is no data available in the database.

As a "skip" I have used the prompt `>>` rather than `>>>`, so this should be changed when data is made available for them somewhere down the line.

blocked by #254 
related #368

**Comment by mwatts15** [comment]
The code there doesn't actually work - should be Channel rather than IonChannel.
