### ISSUE TITLE
"beginner""Question": pytest failed

### ISSUE THREAD

**Issue by gksshcks** [openworm/owmeta#468]
_beginner issue_
Hi. I'm a beginner having a similar issue in #370 and #371. My machine is Unbuntu system
After installing the PyOpenWorm in a conda's virtual environment,  I followed the steps of "Quickstart" in the “README.md“. And then I did Pytest in the owmeta folder which is generated through "git clone". 

But I got similar errors reported in #370 and #371  such that 

> "platform linux -- Python 3.6.12, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
> rootdir: /home/hansol/owmeta, configfile: pytest.ini, testpaths: tests
> collected 154 items                                                            
> 
> tests/BibtexTest.py ........                                             [  5%]
> tests/CellTest.py ..........                                             [ 11%]
> tests/ChannelTest.py .......                                             [ 16%]
> tests/ChannelWormTest.py .....                                           [ 19%]
> tests/CommandTest.py ......                                              [ 23%]
> tests/ConnectionNeurotransmitterDataTranslatorTest.py ....               [ 25%]
> tests/ConnectionTest.py .....                                            [ 29%]
> tests/DWEDSTest.py ..                                                    [ 30%]
> tests/DataIntegrityTest.py FFFFFFFFFFFFFFFFFFFs                          [ 43%]
> tests/DocumentTest.py ...............                                    [ 53%]
> tests/DocumentationTest.py F....                                         [ 56%]
> tests/EvidenceCoverageTest.py sx..                                       [ 59%]
> tests/EvidenceForTest.py ....                                            [ 61%]
> tests/EvidenceQualityTest.py .                                           [ 62%]
> tests/EvidenceTest.py ....                                               [ 64%]
> tests/ExampleRunnerTest.py ..F.F..F                                      [ 70%]
> tests/ExperimentTest.py ...                                              [ 72%]
> tests/MuscleTest.py ...                                                  [ 74%]
> tests/NetworkTest.py ....                                                [ 76%]
> tests/NeuronCSVDataTranslatorTest.py .........                           [ 82%]
> tests/NeuronTest.py .................                                    [ 93%]
> tests/PlotTest.py ...                                                    [ 95%]
> tests/ProfileTest.py ....                                                [ 98%]
> tests/WormTest.py ...                                                    [100%]
> 
> =================================== FAILURES ===================================
>  DataIntegrityTest.test_INS_26_neuropeptide_neuron_list ____________
> 
> bundles_directory = '/root/.owmeta/bundles', ident = 'openworm/owmeta-data'
> version = None
> 
>     def find_bundle_directory(bundles_directory, ident, version=None):
>         # - look up the bundle in the bundle cache
>         # - generate a config based on the current config load the config
>         # - make a database from the graphs, if necessary (similar to `owm regendb`). If
>         #   delete the existing database if it doesn't match the store config
>         if version is None:
>             bundle_root = fmt_bundle_directory(bundles_directory, ident)
>             latest_version = 0
>             try:
> >               ents = scandir(bundle_root)
> E               FileNotFoundError: [Errno 2] No such file or directory: '/root/.owmeta/bundles/openworm%2Fowmeta-data'
> 
> ../anaconda3/envs/ele/lib/python3.6/site-packages/owmeta_core/bundle/common.py:108: FileNotFoundError
> 
> The above exception was the direct cause of the following exception:
> 
> self = <owmeta_core.bundle.Bundle object at 0x7fa1e6e33940>
> 
>     def resolve(self):
>         try:
> >           bundle_directory = self._get_bundle_directory()
> 
> ../anaconda3/envs/ele/lib/python3.6/site-packages/owmeta_core/bundle/__init__.py:409: "

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
---

I tried "pow clone git@github.com:openworm/OpenWormData.git" too, but it gives " Nertz! Nothing matched those labels." It seems there are issues while getting Data from OpenWormData, but I don't know how to fix it.

**Comment by mwatts15** [comment]
Hi, @gksshcks . I think you probably got to some old documentation at some point. I've updated the URL on PyPI and in the readme on the dev branch, but would appreciate if you could point me to where else you saw "PyOpenWorm" and "pow clone..." . I need to rewrite it to be more friendly to folks who aren't actually working on owmeta.

You shouldn't need to run tests that depend on the bundle, or at all if you're just wanting to use owmeta. I've tried to make that more obvious just now with an update on the `dev` branch.

**Comment by gksshcks** [comment]
Thanks for your comments. I got the same results as those of Example in the Readme.md after following the instructions. Also, I didn't see "pow clone" things where else you've already revised.
